import { useEffect, useRef, useState } from 'react'
import { api } from '../../api'
import './TinNoiBat.css'

const reactions = [['Thich', '👍'], ['Yeu_Thich', '❤️'], ['Haha', '😆'], ['Wow', '😮'], ['Buon', '😢'], ['Tuc_Gian', '😡']]
const mediaUrl = path => `${(import.meta.env.VITE_API_BASE_URL || '/api').replace(/\/$/, '')}${path.slice('/api'.length)}`

export default function TinNoiBat() {
  const [stories, setStories] = useState([]); const [selected, setSelected] = useState(null); const [creating, setCreating] = useState(false)
  const [type, setType] = useState('VAN_BAN'); const [content, setContent] = useState(''); const [file, setFile] = useState(null); const [visibility, setVisibility] = useState('Cong_Khai'); const [progress, setProgress] = useState(0); const dialog = useRef(null)
  const load = async () => { const r = await api('/tins', { headers: { Accept: 'application/json' } }); if (r.ok) setStories((await r.json()).data) }
  useEffect(() => { load() }, [])
  useEffect(() => { if (creating || selected) dialog.current?.showModal(); else dialog.current?.close() }, [creating, selected])
  useEffect(() => { if (!selected || selected.LoaiTin === 'VIDEO') return undefined; const started = Date.now(); const timer = setInterval(() => { const value = Math.min(100, (Date.now() - started) / 300); setProgress(value); if (value === 100) setSelected(null) }, 100); return () => clearInterval(timer) }, [selected?.idTin])
  const replace = story => setStories(current => current.map(item => item.idTin === story.idTin ? story : item))
  async function openStory(story) { setProgress(0); setSelected(story); const r = await api(`/tins/${story.idTin}/xem`, { method: 'POST', headers: { Accept: 'application/json' } }); if (r.ok) { const value = (await r.json()).data; setSelected(value); replace(value) } }
  async function react(type) { const r = await api(`/tins/${selected.idTin}/cam-xuc`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ type }) }); if (r.ok) { const value = (await r.json()).data; setSelected(value); replace(value) } }
  async function publish(event) { event.preventDefault(); const data = new FormData(); data.append('LoaiTin', type); data.append('NoiDung', content); data.append('CheDoHienThi', visibility); if (file) data.append('media', file); const r = await api('/tins', { method: 'POST', headers: { Accept: 'application/json' }, body: data }); if (r.ok) { const value = (await r.json()).data; setStories(current => [value, ...current]); setCreating(false); setContent(''); setFile(null) } }
  return <section aria-label="Tin trong 24 giờ"><div className="stories story-list"><button className="story story-button" onClick={() => setCreating(true)}><span className="story-ring">＋</span><small>Đăng tin</small></button>{stories.map(story => <button className="story story-button" key={story.idTin} onClick={() => openStory(story)}><span className="story-ring">{story.LoaiTin === 'ANH' ? <img src={mediaUrl(story.media_url)} alt="" /> : story.LoaiTin === 'VIDEO' ? '▶' : 'Aa'}</span><small>{story.ten_hien_thi}</small></button>)}</div><dialog ref={dialog} className={selected ? 'story-dialog story-fullscreen' : 'story-dialog'} onCancel={event => { event.preventDefault(); setSelected(null); setCreating(false) }}><header><h2>{creating ? 'Đăng tin mới' : selected?.ten_hien_thi}</h2><button onClick={() => { setSelected(null); setCreating(false) }}>✕</button></header>{creating && <form onSubmit={publish}><label>Loại tin<select value={type} onChange={e => { setType(e.target.value); setFile(null) }}><option value="VAN_BAN">Văn bản</option><option value="ANH">Ảnh</option><option value="VIDEO">Video</option></select></label><label>Nội dung<textarea value={content} onChange={e => setContent(e.target.value)} required={type === 'VAN_BAN'} /></label>{type !== 'VAN_BAN' && <input type="file" required accept={type === 'ANH' ? 'image/*' : 'video/mp4,video/webm'} onChange={e => setFile(e.target.files?.[0])} />}<label>Hiển thị<select value={visibility} onChange={e => setVisibility(e.target.value)}><option value="Cong_Khai">Công khai</option><option value="Ban_Be">Bạn bè</option><option value="Chi_Minh_Toi">Chỉ mình tôi</option></select></label><button className="story-submit">Đăng tin</button></form>}{selected && <div className="story-view">{selected.LoaiTin !== 'VIDEO' && <div className="story-progress"><i style={{ width: `${progress}%` }} /></div>}{selected.LoaiTin === 'ANH' && <img className="story-media" src={mediaUrl(selected.media_url)} alt="Tin" />}{selected.LoaiTin === 'VIDEO' && <video className="story-media" src={mediaUrl(selected.media_url)} autoPlay controls onEnded={() => setSelected(null)} />}{selected.NoiDung && <p className={selected.LoaiTin === 'VAN_BAN' ? 'story-text' : ''}>{selected.NoiDung}</p>}<div className="story-footer"><span>{selected.reactions_count || 0} cảm xúc</span>{selected.is_owner && <span>◉ {selected.views_count || 0} lượt xem</span>}</div>{selected.is_owner && selected.viewers?.length > 0 && <div className="story-viewers"><strong>Đã xem</strong>{selected.viewers.map(viewer => <span key={viewer.id}>{viewer.name}</span>)}</div>}<div className="story-reactions">{reactions.map(([key, icon]) => <button className={selected.my_reaction === key ? 'active' : ''} onClick={() => react(key)} key={key}>{icon}</button>)}</div></div>}</dialog></section>
}
